name: 构建镜像并推送到DcokerHub

on: push

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 登录DcokerHub
        uses: docker/login-action@v3 # 利用现成的 action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送到DcokerHub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: zt2tzzt/react-aribnb:latest # 和 dockerhub 仓库对应
